project_name: alug
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/alug/main.go
    binary: alug
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
    goarm:
      - "6"
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
brews:
  - tap:
      owner: shirakiya
      name: homebrew-alug
    homepage: https://github.com/shirakiya/alug
    description: CLI command to generate the URL to login AWS console.
    url_template: https://github.com/shirakiya/alug/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    install: |
      bin.install "alug"
    test: |
      system "#{bin}/alug -v"
