version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
         update_type: "semver:minor"
    default_reviewers:
      - "shirakiya"
    default_labels:
      - "dependabot"
