name: Go
on:
  push:
    paths-ignore:
      - README*
jobs:
  fmt:
    name: go.fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14.2
      - name: Go fmt
        run: make fmt

  test:
    name: go.test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.14.2
      - name: Go test
        run: make test
      - name: Coverage
        run: make coverage
