name: Go
on:
  push:
    paths-ignore:
      - README*
env:
  GO_VERSION: ^1.14.2
jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      RUN_CONTEXT:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Go fmt
        run: make fmt

  lint:
    runs-on: ubuntu-latest
    env:
      RUN_CONTEXT:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
      - name: Go lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      RUN_CONTEXT:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Go test
        run: make test
      - name: Coverage
        run: make coverage

  build_check:
    runs-on: ubuntu-latest
    env:
      RUN_CONTEXT:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make build
      - name: Check executable
        run: ./bin/alug -v
